name: ✨ Feature Request
description: Suggest a feature, script, or improvement
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Got an idea for a feature? Let's make espresso stronger! 🚀

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: Short description of the feature you’re suggesting.
      placeholder: e.g., "Add prompt batch tester script"

  - type: textarea
    id: motivation
    attributes:
      label: Why Is This Needed?
      description: What problem does this solve? How will it help?

  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
      description: Describe what the feature should do.

  - type: dropdown
    id: urgency
    attributes:
      label: How urgent is it?
      options:
        - "Just an idea, no rush"
        - "Would be nice soon"
        - "Urgent / Critical 🚨"
